### ISSUE TITLE
abstract-in-progress

### ISSUE THREAD

**Issue by jessb0t** [jessb0t/motorImagery#3]
#### BACKGROUND
1. movement-related phase amplitude modulation exists during voluntary motor movements
2. imagined motor movement are used to control BCIs, however they require training (implying this is somehow different than a pure motor task)
3. inverse(ish) relationship between beta and gamma in motion and at rest
4. amplitude modulation is related to phase coupling (but we're not sure how...)

#### QUESTION
Do imagined motor movements also demonstrate such amplitude modulation?

#### ISSUES
volume conduction
proprioception as a confound? (visual feedback reintroduced something about beta)

**Comment by kurtlehn1** [comment]
Methods:

Methods

8 “X” subjects with epilepsy underwent craniotomy for placement of subdural electrode arrays for invasive seizure monitoring via electrocortigoraphy (ECoG)  during treatment of medically refractory epilepsy. Array location and duration of implantation were determined by clinical criteria alone. 

5 “Y” patients underwent mapping of the motor cortex with electrical stimulation. 

Subjects participated in two (three?) tasks involving overt or imagined movement with simultaneously ECoG. Data glove and/or EMG was utilized to ensure no movement during imagined tasks. 

Time frequency analysis of the ECoG signal was conducted to create the power spectrum of the signal in the (gamma/beta/alpha/mu/etc). Event related synchrony and descynchrony (ERS/ERD) measurements were determined by relative amplitude changes in respective power spectra during rest and movement. 

Simulated motor movements were utilized to determine the movement phase amplitude modulation…

**Comment by jessb0t** [comment]
MEASUREMENTS
FFT: bandpass filter B1-GX + GH
Hilbert transform
correlate with simulated sine wave for motion on/off
Z-score
calculate MPA: Z-score above chance
